#!/data/data/com.termux/files/usr/bin/bash

pole_znaky=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
pole_znaky+=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
pole_znaky+=(1 2 3 4 5 6 7 8 9 0)


d_pole_znaky=${#pole_znaky[@]}
echo $d_pole_znaky

max=15

key () {
key_out=""
for (( znak = 1; znak <= $max; znak++))
do
rnd=$(( $RANDOM % $d_pole_znaky + 0 ))
key_out+=${pole_znaky[$rnd]}
done
echo $key_out
}

key




