#!/data/data/com.termux/files/usr/bin/bash

s="abcd"

echo $s
echo $s | rev

s2=$( echo $s | rev)
echo $s2

#-------

text="Ahoj Svete"
echo $text
obracene=""
for (( i=${#text} -1; i>=0; i-- ))
do
obracene="$obracene${text:$i:1}"
done
echo $obracene









